<div id="tertCol">
	<div class="middle_links intro">
		<h3>Datavisualization</h3>
		<p>"Data Visualization is a transversal discipline which harnesses the immense power of visual communication in order to explain, in an understandable manner, the relationships of meaning, cause and dependency which can be found among the great abstract masses of information generated by scientific and social processes."</p>
	</div>
	<div class="middle_links">
		<h3>Subscribe</h3>
		<p>Subscribe to the <?php bloginfo('name'); ?> contents via RSS (<a href="http://www.wikipedia.org/wiki/RSS" title="What is RSS?" class="qm">?</a>) or via email.</p>
		<ul class="feed">
			<li><a href="feed:<?php bloginfo('rss2_url'); ?>" title="Subscribe to our articles RSS feed">Articles RSS</a></li>
			<li class="twitter_icon"><a href="http://www.twitter.com/datavisualization" title="Follow us on twitter">Follow on Twitter</a></li>
		</ul>
	</div>
	<?php 
	if(is_home()){
		$before_cat = '<div class="middle_links ext">';
		$after_cat = '</div>';
		wp_list_bookmarks("category_before=$before_cat&category_after=$after_cat&title_before=<h3>&title_after=</h3>&title_li=Links");
	}
	?>
</div><!-- close #tertCol -->